# This workflow will do a clean install of dependencies and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/

name: Doing the Org Export

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Emacs
        uses: purcell/setup-emacs@v3.0
        with:
          # The version of Emacs to install, e.g. "24.3", or "snapshot" for a recent development version.
          version: 27.1 # optional

      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #  run: echo Hello, world!

      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.

      - name: Make the goods ---for now, syntax colouring does not come through; TODO
        shell: 'script --return --quiet --command "bash {0}"'
        run: emacs --script init.el
        # Init.el can be found at
        # https://github.com/alhassy/del/blob/main/init.el.
        # But it is mostly the following:
        # run: emacs -Q -nw index.org --load init.el -eval "(progn (require 'package) (add-to-list 'package-archives '(\"melpa\" . \"http://melpa.org/packages/\")) (setq package-load-list '((htmlize t))) (package-initialize) (load-theme 'adwaita) (org-html-export-to-html))" -f kill-emacs

        env:
          TERM: "xterm"
        # “emacs --batch” inhibits the colorization of the code snippets.
        # Using “emacs -Q -nw” instead does not work with Github Actions :/


      - name: where am I and what's here
        run: |
          pwd
          ls
      # The next step will deploy the “/home/runner/work/del/del” directory to
      # the remote “gh-pages” branch of this repo.
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /home/runner/work/del/del
          force_orphan: true
        # For newbies of GitHub Actions: Note that the GITHUB_TOKEN is NOT a
        # personal access token. A GitHub Actions runner automatically creates a
        # GITHUB_TOKEN secret to authenticate in your workflow. So, you can
        # start to deploy immediately without any configuration.
        #
        # “del” is the name of the repo where I'm trying this out.
